# Render Blueprint
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: employee-mcp-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: AUTHORIZATION_TOKEN
        generateValue: true
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/employees
